* Author: SANJAY JYOTI DUTTA
* Date Created: 21 July 2016
* Environment
  - OS: Windows 7,Ubuntu-16.04,CentOS-6
  - Browsers: Firefox-42.0,Chrome-47.0,Chromium-45.0
  - Bandwidth : 100Mbps
  - Hardware Configuration:8GB RAM , 
  - Processor:i7

* Objective
  - To perform the Experiment of Business Communication experiment

* Pre conditions
  - 1. Open the url vlabs.ac.in and vlabs home page is displayed 
 
    2. Click on IIT-Guwahati and a list of labs is displayed on the screen 
  
    3. Select Other Laboratories (Design & Humanities), a home page is displayed and click on List of experiments link,  where a list of experiments will be displayed on the screen
  
    4. Selecte "Virtual English and Communication" experiment.
    5. Selecte "Communication Skills"
* Post conditions
   - Nill.
* Test Steps
  1. Clicked on the Self Evaluation link
  2. Click on "Exercise" link of "Writing question tags", "Matching the idioms/phrases with their meanings", "Matching the emotions with the facial expressions", "Context matching", "Selecting the appropriate speech style" and "Matching language snippets with appropriate situations".
  
* Expected result
  1. Write the question tags for the following Quiz page is opened.
  2. Match the idioms/phrases with their correct meanings Matching exercise page is opened.
  3. Rewrite the following sentences in the correct form Quiz page is opened.
  4. Rewrite the following sentences by adding the omitted preposition in the correct place Quiz page is opened.
  5. Match the emotions with the facial expressions Matching exercise page is opened.
  6. Match the language snippets on the left column with the appropriate situations on the right Matching exercise page is opened.

* Review comments
