* Author: SANJAY JYOTI DUTTA
* Date Created: 21 July 2016
* Environment
  - OS: Windows 7,Ubuntu-16.04,CentOS-6
  - Browsers: Firefox-42.0,Chrome-47.0,Chromium-45.0
  - Bandwidth : 100Mbps
  - Hardware Configuration:8GB RAM , 
  - Processor:i7

* Objective
  - To perform the Experiment of Grammar

* Pre conditions
  - 1. Open the url vlabs.ac.in and vlabs home page is displayed 
 
    2. Click on IIT-Guwahati and a list of labs is displayed on the screen 
  
    3. Select Other Laboratories (Design & Humanities), a home page is displayed and click on List of experiments link,  where a list of experiments will be displayed on the screen
  
    4. Selecte "Virtual English and Communication" experiment.
    5. Selecte "Grammar"
* Post conditions
   - Nill.
* Test Steps
  1. Clicked on the Self Evaluation link
  2. Click on "Exercise" link of "Writing forms of Adjectives", " Finding the correct Preposition", "Arranging parts to form a sentence", "Finding the error and re-writing a sentence", "Arranging sentences to form a paragraph" and "Selecting the correct Indefinite Article".
  
* Expected result
  1. ADJECTIVES page is opened.
  2. 	Quiz on Prepositions page is opened.
  3. Spot the errors and rewrite the sentence in correct form page is opened.
  4. Arrange the sentences to form a logically coherent paragraph page is opened.
  5. Match the emotions with the facial expressions Matching exercise page is opened.
  6. INDEFINITE ARTICLES page is opened.

* Review comments
